apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: temperature-handler
  name: temperature-handler
spec:
  replicas: 1
  serviceName: temperature-handler
  selector:
    matchLabels:
      app: temperature-handler
  template:
    metadata:
      labels:
        app: temperature-handler
    spec:
      containers:
      - name: temperature-handler
        image: ghcr.io/mmaschenk/docker-temperature-handler:main
        envFrom:
        - secretRef:
            name: passwords
        - configMapRef:
            name: environment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temperature-rgbmatrix-runner
  name: temperature-rgbmatrix-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: temperature-rgbmatrix-runner
  template:
    metadata:
      labels:
        app: temperature-rgbmatrix-runner
    spec:
      containers:
      - name: temperature-rgbmatrix-runner
        image: ghcr.io/mmaschenk/docker-temperature-handler:main
        envFrom:
        - secretRef:
            name: passwords
        - configMapRef:
            name: environment
        command: [ "python" ]
        args: [ "-u", "/temperature_rgbmatrix.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temperature-elasticsearch-runner
  name: temperature-elasticsearch-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: temperature-elasticsearch-runner
  template:
    metadata:
      labels:
        app: temperature-elasticsearch-runner
    spec:
      containers:
      - name: temperature-elasticsearch-runner
        image: ghcr.io/mmaschenk/docker-temperature-handler:main
        envFrom:
        - secretRef:
            name: passwords
        - configMapRef:
            name: environment
        command: [ "python" ]
        args: [ "-u", "/temperature_elasticsearch.py"]
